<?php

/**
 * This file is licensed under MIT License.
 *
 * Copyright (c) 2026-present WebFiori Framework.
 *
 * For more information on the license, please visit:
 * https://github.com/WebFiori/ai/blob/main/LICENSE
 */
namespace WebFiori\Ai\Provider;

use WebFiori\Ai\ChatResponse;
use WebFiori\Ai\EmbeddingResponse;
use WebFiori\Ai\ImageRequest;
use WebFiori\Ai\ImageResponse;
use WebFiori\Ai\Message;

/**
 * Contract for AI provider implementations.
 *
 * This interface defines the common operations that all AI providers
 * (OpenAI, Google, Anthropic, Bedrock) must implement. Providers
 * that do not support a specific operation should throw
 * {@see \WebFiori\Ai\Exception\UnsupportedFeatureException}.
 *
 * @author Ibrahim
 */
interface ProviderInterface {
    /**
     * Sends a chat completion request and returns the full response.
     *
     * @param Message[] $messages An array of messages forming the conversation.
     * @param array<string, mixed> $options Additional provider-specific options
     *        (e.g., temperature, max_tokens, model override).
     *
     * @return ChatResponse The AI-generated response.
     *
     * @throws \WebFiori\Ai\Exception\AuthenticationException If credentials are invalid.
     * @throws \WebFiori\Ai\Exception\RateLimitException If the rate limit is exceeded.
     * @throws \WebFiori\Ai\Exception\ProviderException If the provider returns an error.
     * @throws \WebFiori\Ai\Exception\HttpException If a transport error occurs.
     */
    public function chat(array $messages, array $options = []): ChatResponse;

    /**
     * Generates vector embeddings for the given text input.
     *
     * @param string|string[] $input A single text string or an array of strings
     *        to generate embeddings for.
     * @param array<string, mixed> $options Additional provider-specific options
     *        (e.g., model override, dimensions).
     *
     * @return EmbeddingResponse The embedding response containing vector(s).
     *
     * @throws \WebFiori\Ai\Exception\UnsupportedFeatureException If the provider
     *         does not support embeddings.
     * @throws \WebFiori\Ai\Exception\ProviderException If the provider returns an error.
     */
    public function embed(string|array $input, array $options = []): EmbeddingResponse;

    /**
     * Generates an image from a text prompt.
     *
     * @param ImageRequest $request The image generation request containing
     *        prompt, size, quality, and other options.
     *
     * @return ImageResponse The response containing generated image(s).
     *
     * @throws \WebFiori\Ai\Exception\UnsupportedFeatureException If the provider
     *         does not support image generation.
     * @throws \WebFiori\Ai\Exception\ProviderException If the provider returns an error.
     */
    public function generateImage(ImageRequest $request): ImageResponse;

    /**
     * Returns the name of the provider.
     *
     * @return string A human-readable provider name (e.g., 'openai', 'google').
     */
    public function getName(): string;

    /**
     * Sets the HTTP client used for making API requests.
     *
     * This allows injection of custom or mock HTTP clients for testing.
     *
     * @param \WebFiori\Ai\Http\HttpClientInterface $client The HTTP client to use.
     */
    public function setHttpClient(\WebFiori\Ai\Http\HttpClientInterface $client): void;

    /**
     * Sets a callback function for logging.
     *
     * The callback receives log entries with level, message, and context.
     * If no callback is set, no logging occurs.
     *
     * @param callable|null $callback The logging callback with signature:
     *        function(string $level, string $message, array $context): void
     *        Pass null to disable logging.
     */
    public function setLogCallback(?callable $callback): void;

    /**
     * Sends a chat completion request with streaming response.
     *
     * Tokens are delivered incrementally via the onToken callback as they
     * are generated by the AI model.
     *
     * @param Message[] $messages An array of messages forming the conversation.
     * @param callable $onToken Callback invoked for each token received.
     *        Signature: function(string $token): void
     * @param callable|null $onComplete Optional callback invoked when streaming
     *        completes. Signature: function(ChatResponse $response): void
     * @param callable|null $onError Optional callback invoked on stream error.
     *        Signature: function(\WebFiori\Ai\Exception\StreamingException $e): void
     * @param array<string, mixed> $options Additional provider-specific options.
     *
     * @throws \WebFiori\Ai\Exception\AuthenticationException If credentials are invalid.
     * @throws \WebFiori\Ai\Exception\RateLimitException If the rate limit is exceeded.
     * @throws \WebFiori\Ai\Exception\ProviderException If the provider returns an error.
     */
    public function streamChat(
        array $messages,
        callable $onToken,
        ?callable $onComplete = null,
        ?callable $onError = null,
        array $options = []
    ): void;
}
