<?php

/**
 * This file is licensed under MIT License.
 *
 * Copyright (c) 2026-present WebFiori Framework.
 *
 * For more information on the license, please visit:
 * https://github.com/WebFiori/ai/blob/main/LICENSE
 */
namespace WebFiori\Ai;

/**
 * Represents the role of a message sender in a conversation.
 *
 * Each message in a chat conversation has a role that identifies who
 * sent it. This enum provides type-safe role values that are compatible
 * with all supported AI providers.
 *
 * @author Ibrahim
 */
enum Role: string {
    /**
     * The AI assistant role. Messages generated by the AI model.
     */
    case ASSISTANT = 'assistant';

    /**
     * The system role. Used for system instructions that guide model behavior.
     */
    case SYSTEM = 'system';

    /**
     * The tool role. Used for tool/function execution results returned to the model.
     */
    case TOOL = 'tool';

    /**
     * The user role. Messages sent by the human user.
     */
    case USER = 'user';
}
